"""Type stubs for the native module."""

from collections.abc import Iterator, Sequence
from types import TracebackType
from typing import Any, final

__all__ = [
    "Caps",
    "Location",
    "Sink",
    "Source",
    "Tensor",
    "Verification",
    "Writer",
    "convert",
    "detect",
    "index",
    "open",
    "page_size",
    "verify",
]

@final
class Caps:
    """What one part can do. Each field is the precondition of the operation
    it names."""

    @property
    def map(self) -> bool: ...
    @property
    def locate(self) -> bool: ...
    @property
    def evict(self) -> bool: ...
    @property
    def verify(self) -> bool: ...
    @property
    def alignment(self) -> int: ...

@final
class Location:
    """Where a part's bytes are."""

    @property
    def path(self) -> str: ...
    @property
    def offset(self) -> int: ...
    @property
    def nbytes(self) -> int: ...

@final
class Verification:
    """How much of a file carried a digest. Unpacks as a pair."""

    @property
    def checked(self) -> int: ...
    @property
    def undigested(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> int: ...

@final
class Tensor:
    """One tensor, or one part of one.

    A tensor with a single part resolves to it, so the byte members below work
    directly. A tensor with several does not: index the part you mean, as
    ``t["scales"]``.
    """

    @property
    def name(self) -> str: ...
    @property
    def part(self) -> str | None: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def logical(self) -> str | None: ...
    @property
    def layout(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def parts(self) -> list[str]: ...
    @property
    def caps(self) -> Caps: ...
    @property
    def location(self) -> Location: ...
    def __getitem__(self, part: str, /) -> Tensor: ...
    def tobytes(self) -> bytes: ...
    def verify(self) -> bool: ...
    def prefetch(self) -> None: ...
    def evict(self) -> None: ...
    def __dlpack__(
        self,
        stream: object | None = ...,
        *,
        max_version: tuple[int, int] | None = ...,
        dl_device: tuple[int, int] | None = ...,
        copy: bool | None = ...,
    ) -> object: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...

@final
class Source:
    """A tensor file, or several read as one. A mapping from name to tensor."""

    def keys(self) -> list[str]: ...
    def values(self) -> list[Tensor]: ...
    def items(self) -> list[tuple[str, Tensor]]: ...
    def get(self, name: str, default: Any = ...) -> Any: ...
    @property
    def files(self) -> list[str]: ...
    @property
    def attributes(self) -> object | None: ...
    @property
    def provenance(self) -> str: ...
    def verify(self, deep: bool = ...) -> Verification: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str, /) -> bool: ...
    def __getitem__(self, name: str, /) -> Tensor: ...
    def __iter__(self) -> Iterator[str]: ...
    def __enter__(self) -> Source: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...

@final
class Sink:
    """Accepts the bytes of a streamed object, in part-name order."""

    def write(self, chunk: object) -> None: ...
    @property
    def part(self) -> str | None: ...
    @property
    def written(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Sink: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...

@final
class Writer:
    """Writes `.zt` files."""

    def __new__(
        cls,
        path: str,
        canonical: bool = ...,
        align: int | None = ...,
        publish: bool = ...,
        append: bool = ...,
    ) -> Writer: ...
    def add(
        self,
        name: str,
        data: object,
        shape: Sequence[int],
        dtype: str,
        logical: str | None = ...,
        encoding: str | None = ...,
    ) -> None: ...
    def add_object(
        self,
        name: str,
        shape: Sequence[int],
        parts: dict[str, dict[str, object]],
        layout: str = ...,
        attributes: dict[str, object] | None = ...,
    ) -> None: ...
    def stream(
        self,
        name: str,
        shape: Sequence[int],
        parts: dict[str, dict[str, object]],
        layout: str = ...,
        attributes: dict[str, object] | None = ...,
    ) -> Sink: ...
    def set_attributes(self, attributes: dict[str, object]) -> None: ...
    def ingest(self, source: Source) -> None: ...
    def finish(self) -> int: ...
    def abandon(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...

def open(paths: str | Sequence[str]) -> Source: ...
def index(paths: str | Sequence[str]) -> Source: ...
def detect(path: str) -> str: ...
def convert(src: str, dst: str, align: int | None = ...) -> int: ...
def verify(path: str, deep: bool = ...) -> Verification: ...
def page_size() -> int: ...
